#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
#
Name     : waypipe
Version  : 0.8.6
Release  : 4
URL      : https://gitlab.freedesktop.org/mstoeckl/waypipe/-/archive/v0.8.6/waypipe-v0.8.6.tar.gz
Source0  : https://gitlab.freedesktop.org/mstoeckl/waypipe/-/archive/v0.8.6/waypipe-v0.8.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: waypipe-bin = %{version}-%{release}
Requires: waypipe-license = %{version}-%{release}
Requires: waypipe-man = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : libva-dev
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(libavcodec)
BuildRequires : pkgconfig(libavutil)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(libswscale)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libzstd)
BuildRequires : pkgconfig(scdoc)
BuildRequires : pkgconfig(weston)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Waypipe
================================================================================

%package bin
Summary: bin components for the waypipe package.
Group: Binaries
Requires: waypipe-license = %{version}-%{release}

%description bin
bin components for the waypipe package.


%package license
Summary: license components for the waypipe package.
Group: Default

%description license
license components for the waypipe package.


%package man
Summary: man components for the waypipe package.
Group: Default

%description man
man components for the waypipe package.


%prep
%setup -q -n waypipe-v0.8.6
cd %{_builddir}/waypipe-v0.8.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1690815072
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/waypipe
cp %{_builddir}/waypipe-v%{version}/COPYING %{buildroot}/usr/share/package-licenses/waypipe/4d65516895ecd648f06b90c41ff0e6b578531451 || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/waypipe

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/waypipe/4d65516895ecd648f06b90c41ff0e6b578531451

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/waypipe.1
